version: '3.7'

services:
    slim:
        image: php:8.2-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public/
        environment:
            docker: "true"
        ports:
            - "${WEB_PORT:-8080}:8080"
        volumes:
            - .:/var/www
